sudo: required

language: c

compiler:
- gcc
- clang

services:
- docker

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - procps-ng
  - reflector
  - hwinfo
  # aur
  - screenfetch-git
  script:
  - "sudo screenfetch"
  - "hwinfo"
  - "reflector --verbose -l 20 --sort rate -p https"
  - "echo $CC"
  - "touch test_file"

script:
- "bash ./arch-travis.sh"
- "ls -l"
